/*出装图片切换板块*/

var i=0;
function hero(i){
	var a=document.getElementById("a1");
	if(i==0)
	a.setAttribute("src","images/上官婉儿出装铭文.jpg");
	if(i==1)
	a.setAttribute("src","images/狄仁杰出装铭文.jpg");
	if(i==2)
	a.setAttribute("src","images/蔡文姬出装铭文.jpg");
	if(i==3)
	a.setAttribute("src","images/夏侯惇出装铭文.jpg");
	if(i==4)
	a.setAttribute("src","images/嫦娥出装铭文.jpg");
	if(i==5)
	a.setAttribute("src","images/狂铁出装铭文.jpg");
	if(i==6)
	a.setAttribute("src","images/阿珂出装铭文.jpg");
	if(i==7)
	a.setAttribute("src","images/铠出装铭文.jpg");
	if(i==8)
	a.setAttribute("src","images/嬴政出装铭文.jpg");
	if(i==9)
	a.setAttribute("src","images/安琪拉出装铭文.jpg");
	if(i==10)
	a.setAttribute("src","images/西施出装铭文.jpg");
	if(i==11)
	a.setAttribute("src","images/甄姬出装铭文.jpg");
	if(i==12)
	a.setAttribute("src","images/马可波罗出装铭文.jpg");
	if(i==13)
	a.setAttribute("src","images/孙悟空出装铭文.jpg");
	if(i==14)
	a.setAttribute("src","images/百里守约出装铭文.jpg");
	if(i==15)
	a.setAttribute("src","images/黄忠出装铭文.jpg");
	if(i==16)
	a.setAttribute("src","images/庄周出装铭文.jpg");
	if(i==17)
	a.setAttribute("src","images/盘古出装铭文.jpg");
	if(i==18)
	a.setAttribute("src","images/张良出装铭文.jpg");
	if(i==19)
	a.setAttribute("src","images/貂蝉出装铭文.jpg");
	if(i==20)
	a.setAttribute("src","images/百里玄策出装铭文.jpg");
	if(i==21)
	a.setAttribute("src","images/姜子牙出装铭文.jpg");
	if(i==22)
	a.setAttribute("src","images/李信出装铭文.jpg");
	if(i==23)
	a.setAttribute("src","images/明世隐出装铭文.jpg");
	if(i==24)
	a.setAttribute("src","images/武则天出装铭文.jpg");
	if(i==25)
	a.setAttribute("src","images/雅典娜出装铭文.jpg");
	if(i==26)
	a.setAttribute("src","images/成吉思汗出装铭文.jpg");
	if(i==27)
	a.setAttribute("src","images/裴擒虎出装铭文.jpg");
	if(i==28)
	a.setAttribute("src","images/程咬金出装铭文.jpg");
	if(i==29)
	a.setAttribute("src","images/橘右京出装铭文.jpg");
	if(i==30)
	a.setAttribute("src","images/瑶出装铭文.jpg");
	if(i==31)
	a.setAttribute("src","images/鬼谷子出装铭文.jpg");
	if(i==32)
	a.setAttribute("src","images/艾琳出装铭文.jpg");
}